// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preferences.proto

package androidx.datastore.preferences;

public final class PreferencesProto {
  private PreferencesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PreferenceMapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:androidx.testing.PreferenceMap)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>map&lt;string, .androidx.testing.Value&gt; preferences = 1;</code>
     */
    int getPreferencesCount();
    /**
     * <code>map&lt;string, .androidx.testing.Value&gt; preferences = 1;</code>
     */
    boolean containsPreferences(
        java.lang.String key);
    /**
     * Use {@link #getPreferencesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, androidx.datastore.preferences.PreferencesProto.Value>
    getPreferences();
    /**
     * <code>map&lt;string, .androidx.testing.Value&gt; preferences = 1;</code>
     */
    java.util.Map<java.lang.String, androidx.datastore.preferences.PreferencesProto.Value>
    getPreferencesMap();
    /**
     * <code>map&lt;string, .androidx.testing.Value&gt; preferences = 1;</code>
     */

    androidx.datastore.preferences.PreferencesProto.Value getPreferencesOrDefault(
        java.lang.String key,
        androidx.datastore.preferences.PreferencesProto.Value defaultValue);
    /**
     * <code>map&lt;string, .androidx.testing.Value&gt; preferences = 1;</code>
     */

    androidx.datastore.preferences.PreferencesProto.Value getPreferencesOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code androidx.testing.PreferenceMap}
   */
  public  static final class PreferenceMap extends
      com.google.protobuf.GeneratedMessageLite<
          PreferenceMap, PreferenceMap.Builder> implements
      // @@protoc_insertion_point(message_implements:androidx.testing.PreferenceMap)
      PreferenceMapOrBuilder {
    private PreferenceMap() {
    }
    public static final int PREFERENCES_FIELD_NUMBER = 1;
    private static final class PreferencesDefaultEntryHolder {
      static final com.google.protobuf.MapEntryLite<
          java.lang.String, androidx.datastore.preferences.PreferencesProto.Value> defaultEntry =
              com.google.protobuf.MapEntryLite
              .<java.lang.String, androidx.datastore.preferences.PreferencesProto.Value>newDefaultInstance(
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  androidx.datastore.preferences.PreferencesProto.Value.getDefaultInstance());
    }
    private com.google.protobuf.MapFieldLite<
        java.lang.String, androidx.datastore.preferences.PreferencesProto.Value> preferences_ =
            com.google.protobuf.MapFieldLite.emptyMapField();
    private com.google.protobuf.MapFieldLite<java.lang.String, androidx.datastore.preferences.PreferencesProto.Value>
    internalGetPreferences() {
      return preferences_;
    }
    private com.google.protobuf.MapFieldLite<java.lang.String, androidx.datastore.preferences.PreferencesProto.Value>
    internalGetMutablePreferences() {
      if (!preferences_.isMutable()) {
        preferences_ = preferences_.mutableCopy();
      }
      return preferences_;
    }
    @java.lang.Override

    public int getPreferencesCount() {
      return internalGetPreferences().size();
    }
    /**
     * <code>map&lt;string, .androidx.testing.Value&gt; preferences = 1;</code>
     */
    @java.lang.Override

    public boolean containsPreferences(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetPreferences().containsKey(key);
    }
    /**
     * Use {@link #getPreferencesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, androidx.datastore.preferences.PreferencesProto.Value> getPreferences() {
      return getPreferencesMap();
    }
    /**
     * <code>map&lt;string, .androidx.testing.Value&gt; preferences = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, androidx.datastore.preferences.PreferencesProto.Value> getPreferencesMap() {
      return java.util.Collections.unmodifiableMap(
          internalGetPreferences());
    }
    /**
     * <code>map&lt;string, .androidx.testing.Value&gt; preferences = 1;</code>
     */
    @java.lang.Override

    public androidx.datastore.preferences.PreferencesProto.Value getPreferencesOrDefault(
        java.lang.String key,
        androidx.datastore.preferences.PreferencesProto.Value defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, androidx.datastore.preferences.PreferencesProto.Value> map =
          internalGetPreferences();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .androidx.testing.Value&gt; preferences = 1;</code>
     */
    @java.lang.Override

    public androidx.datastore.preferences.PreferencesProto.Value getPreferencesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, androidx.datastore.preferences.PreferencesProto.Value> map =
          internalGetPreferences();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, .androidx.testing.Value&gt; preferences = 1;</code>
     */
    private java.util.Map<java.lang.String, androidx.datastore.preferences.PreferencesProto.Value>
    getMutablePreferencesMap() {
      return internalGetMutablePreferences();
    }

    public static androidx.datastore.preferences.PreferencesProto.PreferenceMap parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static androidx.datastore.preferences.PreferencesProto.PreferenceMap parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static androidx.datastore.preferences.PreferencesProto.PreferenceMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static androidx.datastore.preferences.PreferencesProto.PreferenceMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static androidx.datastore.preferences.PreferencesProto.PreferenceMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static androidx.datastore.preferences.PreferencesProto.PreferenceMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static androidx.datastore.preferences.PreferencesProto.PreferenceMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static androidx.datastore.preferences.PreferencesProto.PreferenceMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static androidx.datastore.preferences.PreferencesProto.PreferenceMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static androidx.datastore.preferences.PreferencesProto.PreferenceMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static androidx.datastore.preferences.PreferencesProto.PreferenceMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static androidx.datastore.preferences.PreferencesProto.PreferenceMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(androidx.datastore.preferences.PreferencesProto.PreferenceMap prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code androidx.testing.PreferenceMap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          androidx.datastore.preferences.PreferencesProto.PreferenceMap, Builder> implements
        // @@protoc_insertion_point(builder_implements:androidx.testing.PreferenceMap)
        androidx.datastore.preferences.PreferencesProto.PreferenceMapOrBuilder {
      // Construct using androidx.datastore.preferences.PreferencesProto.PreferenceMap.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      @java.lang.Override

      public int getPreferencesCount() {
        return instance.getPreferencesMap().size();
      }
      /**
       * <code>map&lt;string, .androidx.testing.Value&gt; preferences = 1;</code>
       */
      @java.lang.Override

      public boolean containsPreferences(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return instance.getPreferencesMap().containsKey(key);
      }

      public Builder clearPreferences() {
        copyOnWrite();
        instance.getMutablePreferencesMap().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .androidx.testing.Value&gt; preferences = 1;</code>
       */

      public Builder removePreferences(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        copyOnWrite();
        instance.getMutablePreferencesMap().remove(key);
        return this;
      }
      /**
       * Use {@link #getPreferencesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, androidx.datastore.preferences.PreferencesProto.Value> getPreferences() {
        return getPreferencesMap();
      }
      /**
       * <code>map&lt;string, .androidx.testing.Value&gt; preferences = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, androidx.datastore.preferences.PreferencesProto.Value> getPreferencesMap() {
        return java.util.Collections.unmodifiableMap(
            instance.getPreferencesMap());
      }
      /**
       * <code>map&lt;string, .androidx.testing.Value&gt; preferences = 1;</code>
       */
      @java.lang.Override

      public androidx.datastore.preferences.PreferencesProto.Value getPreferencesOrDefault(
          java.lang.String key,
          androidx.datastore.preferences.PreferencesProto.Value defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, androidx.datastore.preferences.PreferencesProto.Value> map =
            instance.getPreferencesMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .androidx.testing.Value&gt; preferences = 1;</code>
       */
      @java.lang.Override

      public androidx.datastore.preferences.PreferencesProto.Value getPreferencesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, androidx.datastore.preferences.PreferencesProto.Value> map =
            instance.getPreferencesMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;string, .androidx.testing.Value&gt; preferences = 1;</code>
       */
      public Builder putPreferences(
          java.lang.String key,
          androidx.datastore.preferences.PreferencesProto.Value value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        copyOnWrite();
        instance.getMutablePreferencesMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .androidx.testing.Value&gt; preferences = 1;</code>
       */
      public Builder putAllPreferences(
          java.util.Map<java.lang.String, androidx.datastore.preferences.PreferencesProto.Value> values) {
        copyOnWrite();
        instance.getMutablePreferencesMap().putAll(values);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:androidx.testing.PreferenceMap)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new androidx.datastore.preferences.PreferencesProto.PreferenceMap();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "preferences_",
              PreferencesDefaultEntryHolder.defaultEntry,
            };
            java.lang.String info =
                "\u0001\u0001\u0000\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u00012";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<androidx.datastore.preferences.PreferencesProto.PreferenceMap> parser = PARSER;
          if (parser == null) {
            synchronized (androidx.datastore.preferences.PreferencesProto.PreferenceMap.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<androidx.datastore.preferences.PreferencesProto.PreferenceMap>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:androidx.testing.PreferenceMap)
    private static final androidx.datastore.preferences.PreferencesProto.PreferenceMap DEFAULT_INSTANCE;
    static {
      PreferenceMap defaultInstance = new PreferenceMap();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PreferenceMap.class, defaultInstance);
    }

    public static androidx.datastore.preferences.PreferencesProto.PreferenceMap getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PreferenceMap> PARSER;

    public static com.google.protobuf.Parser<PreferenceMap> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:androidx.testing.Value)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional bool boolean = 1;</code>
     * @return Whether the boolean field is set.
     */
    boolean hasBoolean();
    /**
     * <code>optional bool boolean = 1;</code>
     * @return The boolean.
     */
    boolean getBoolean();

    /**
     * <code>optional float float = 2;</code>
     * @return Whether the float field is set.
     */
    boolean hasFloat();
    /**
     * <code>optional float float = 2;</code>
     * @return The float.
     */
    float getFloat();

    /**
     * <code>optional int32 integer = 3;</code>
     * @return Whether the integer field is set.
     */
    boolean hasInteger();
    /**
     * <code>optional int32 integer = 3;</code>
     * @return The integer.
     */
    int getInteger();

    /**
     * <code>optional int64 long = 4;</code>
     * @return Whether the long field is set.
     */
    boolean hasLong();
    /**
     * <code>optional int64 long = 4;</code>
     * @return The long.
     */
    long getLong();

    /**
     * <code>optional string string = 5;</code>
     * @return Whether the string field is set.
     */
    boolean hasString();
    /**
     * <code>optional string string = 5;</code>
     * @return The string.
     */
    java.lang.String getString();
    /**
     * <code>optional string string = 5;</code>
     * @return The bytes for string.
     */
    com.google.protobuf.ByteString
        getStringBytes();

    /**
     * <code>optional .androidx.testing.StringSet string_set = 6;</code>
     * @return Whether the stringSet field is set.
     */
    boolean hasStringSet();
    /**
     * <code>optional .androidx.testing.StringSet string_set = 6;</code>
     * @return The stringSet.
     */
    androidx.datastore.preferences.PreferencesProto.StringSet getStringSet();

    /**
     * <code>optional double double = 7;</code>
     * @return Whether the double field is set.
     */
    boolean hasDouble();
    /**
     * <code>optional double double = 7;</code>
     * @return The double.
     */
    double getDouble();

    public androidx.datastore.preferences.PreferencesProto.Value.ValueCase getValueCase();
  }
  /**
   * Protobuf type {@code androidx.testing.Value}
   */
  public  static final class Value extends
      com.google.protobuf.GeneratedMessageLite<
          Value, Value.Builder> implements
      // @@protoc_insertion_point(message_implements:androidx.testing.Value)
      ValueOrBuilder {
    private Value() {
    }
    private int bitField0_;
    private int valueCase_ = 0;
    private java.lang.Object value_;
    public enum ValueCase {
      BOOLEAN(1),
      FLOAT(2),
      INTEGER(3),
      LONG(4),
      STRING(5),
      STRING_SET(6),
      DOUBLE(7),
      VALUE_NOT_SET(0);
      private final int value;
      private ValueCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValueCase valueOf(int value) {
        return forNumber(value);
      }

      public static ValueCase forNumber(int value) {
        switch (value) {
          case 1: return BOOLEAN;
          case 2: return FLOAT;
          case 3: return INTEGER;
          case 4: return LONG;
          case 5: return STRING;
          case 6: return STRING_SET;
          case 7: return DOUBLE;
          case 0: return VALUE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    @java.lang.Override
    public ValueCase
    getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    private void clearValue() {
      valueCase_ = 0;
      value_ = null;
    }

    public static final int BOOLEAN_FIELD_NUMBER = 1;
    /**
     * <code>optional bool boolean = 1;</code>
     * @return Whether the boolean field is set.
     */
    @java.lang.Override
    public boolean hasBoolean() {
      return valueCase_ == 1;
    }
    /**
     * <code>optional bool boolean = 1;</code>
     * @return The boolean.
     */
    @java.lang.Override
    public boolean getBoolean() {
      if (valueCase_ == 1) {
        return (java.lang.Boolean) value_;
      }
      return false;
    }
    /**
     * <code>optional bool boolean = 1;</code>
     * @param value The boolean to set.
     */
    private void setBoolean(boolean value) {
      valueCase_ = 1;
      value_ = value;
    }
    /**
     * <code>optional bool boolean = 1;</code>
     */
    private void clearBoolean() {
      if (valueCase_ == 1) {
        valueCase_ = 0;
        value_ = null;
      }
    }

    public static final int FLOAT_FIELD_NUMBER = 2;
    /**
     * <code>optional float float = 2;</code>
     * @return Whether the float field is set.
     */
    @java.lang.Override
    public boolean hasFloat() {
      return valueCase_ == 2;
    }
    /**
     * <code>optional float float = 2;</code>
     * @return The float.
     */
    @java.lang.Override
    public float getFloat() {
      if (valueCase_ == 2) {
        return (java.lang.Float) value_;
      }
      return 0F;
    }
    /**
     * <code>optional float float = 2;</code>
     * @param value The float to set.
     */
    private void setFloat(float value) {
      valueCase_ = 2;
      value_ = value;
    }
    /**
     * <code>optional float float = 2;</code>
     */
    private void clearFloat() {
      if (valueCase_ == 2) {
        valueCase_ = 0;
        value_ = null;
      }
    }

    public static final int INTEGER_FIELD_NUMBER = 3;
    /**
     * <code>optional int32 integer = 3;</code>
     * @return Whether the integer field is set.
     */
    @java.lang.Override
    public boolean hasInteger() {
      return valueCase_ == 3;
    }
    /**
     * <code>optional int32 integer = 3;</code>
     * @return The integer.
     */
    @java.lang.Override
    public int getInteger() {
      if (valueCase_ == 3) {
        return (java.lang.Integer) value_;
      }
      return 0;
    }
    /**
     * <code>optional int32 integer = 3;</code>
     * @param value The integer to set.
     */
    private void setInteger(int value) {
      valueCase_ = 3;
      value_ = value;
    }
    /**
     * <code>optional int32 integer = 3;</code>
     */
    private void clearInteger() {
      if (valueCase_ == 3) {
        valueCase_ = 0;
        value_ = null;
      }
    }

    public static final int LONG_FIELD_NUMBER = 4;
    /**
     * <code>optional int64 long = 4;</code>
     * @return Whether the long field is set.
     */
    @java.lang.Override
    public boolean hasLong() {
      return valueCase_ == 4;
    }
    /**
     * <code>optional int64 long = 4;</code>
     * @return The long.
     */
    @java.lang.Override
    public long getLong() {
      if (valueCase_ == 4) {
        return (java.lang.Long) value_;
      }
      return 0L;
    }
    /**
     * <code>optional int64 long = 4;</code>
     * @param value The long to set.
     */
    private void setLong(long value) {
      valueCase_ = 4;
      value_ = value;
    }
    /**
     * <code>optional int64 long = 4;</code>
     */
    private void clearLong() {
      if (valueCase_ == 4) {
        valueCase_ = 0;
        value_ = null;
      }
    }

    public static final int STRING_FIELD_NUMBER = 5;
    /**
     * <code>optional string string = 5;</code>
     * @return Whether the string field is set.
     */
    @java.lang.Override
    public boolean hasString() {
      return valueCase_ == 5;
    }
    /**
     * <code>optional string string = 5;</code>
     * @return The string.
     */
    @java.lang.Override
    public java.lang.String getString() {
      java.lang.String ref = "";
      if (valueCase_ == 5) {
        ref = (java.lang.String) value_;
      }
      return ref;
    }
    /**
     * <code>optional string string = 5;</code>
     * @return The bytes for string.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringBytes() {
      java.lang.String ref = "";
      if (valueCase_ == 5) {
        ref = (java.lang.String) value_;
      }
      return com.google.protobuf.ByteString.copyFromUtf8(ref);
    }
    /**
     * <code>optional string string = 5;</code>
     * @param value The string to set.
     */
    private void setString(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 5;
      value_ = value;
    }
    /**
     * <code>optional string string = 5;</code>
     */
    private void clearString() {
      if (valueCase_ == 5) {
        valueCase_ = 0;
        value_ = null;
      }
    }
    /**
     * <code>optional string string = 5;</code>
     * @param value The bytes for string to set.
     */
    private void setStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 5;
      value_ = value.toStringUtf8();
    }

    public static final int STRING_SET_FIELD_NUMBER = 6;
    /**
     * <code>optional .androidx.testing.StringSet string_set = 6;</code>
     */
    @java.lang.Override
    public boolean hasStringSet() {
      return valueCase_ == 6;
    }
    /**
     * <code>optional .androidx.testing.StringSet string_set = 6;</code>
     */
    @java.lang.Override
    public androidx.datastore.preferences.PreferencesProto.StringSet getStringSet() {
      if (valueCase_ == 6) {
         return (androidx.datastore.preferences.PreferencesProto.StringSet) value_;
      }
      return androidx.datastore.preferences.PreferencesProto.StringSet.getDefaultInstance();
    }
    /**
     * <code>optional .androidx.testing.StringSet string_set = 6;</code>
     */
    private void setStringSet(androidx.datastore.preferences.PreferencesProto.StringSet value) {
      if (value == null) {
        throw new NullPointerException();
      }
      value_ = value;
      valueCase_ = 6;
    }
    /**
     * <code>optional .androidx.testing.StringSet string_set = 6;</code>
     */
    private void setStringSet(
        androidx.datastore.preferences.PreferencesProto.StringSet.Builder builderForValue) {
      value_ = builderForValue.build();
      valueCase_ = 6;
    }
    /**
     * <code>optional .androidx.testing.StringSet string_set = 6;</code>
     */
    private void mergeStringSet(androidx.datastore.preferences.PreferencesProto.StringSet value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (valueCase_ == 6 &&
          value_ != androidx.datastore.preferences.PreferencesProto.StringSet.getDefaultInstance()) {
        value_ = androidx.datastore.preferences.PreferencesProto.StringSet.newBuilder((androidx.datastore.preferences.PreferencesProto.StringSet) value_)
            .mergeFrom(value).buildPartial();
      } else {
        value_ = value;
      }
      valueCase_ = 6;
    }
    /**
     * <code>optional .androidx.testing.StringSet string_set = 6;</code>
     */
    private void clearStringSet() {
      if (valueCase_ == 6) {
        valueCase_ = 0;
        value_ = null;
      }
    }

    public static final int DOUBLE_FIELD_NUMBER = 7;
    /**
     * <code>optional double double = 7;</code>
     * @return Whether the double field is set.
     */
    @java.lang.Override
    public boolean hasDouble() {
      return valueCase_ == 7;
    }
    /**
     * <code>optional double double = 7;</code>
     * @return The double.
     */
    @java.lang.Override
    public double getDouble() {
      if (valueCase_ == 7) {
        return (java.lang.Double) value_;
      }
      return 0D;
    }
    /**
     * <code>optional double double = 7;</code>
     * @param value The double to set.
     */
    private void setDouble(double value) {
      valueCase_ = 7;
      value_ = value;
    }
    /**
     * <code>optional double double = 7;</code>
     */
    private void clearDouble() {
      if (valueCase_ == 7) {
        valueCase_ = 0;
        value_ = null;
      }
    }

    public static androidx.datastore.preferences.PreferencesProto.Value parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static androidx.datastore.preferences.PreferencesProto.Value parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static androidx.datastore.preferences.PreferencesProto.Value parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static androidx.datastore.preferences.PreferencesProto.Value parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static androidx.datastore.preferences.PreferencesProto.Value parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static androidx.datastore.preferences.PreferencesProto.Value parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static androidx.datastore.preferences.PreferencesProto.Value parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static androidx.datastore.preferences.PreferencesProto.Value parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static androidx.datastore.preferences.PreferencesProto.Value parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static androidx.datastore.preferences.PreferencesProto.Value parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static androidx.datastore.preferences.PreferencesProto.Value parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static androidx.datastore.preferences.PreferencesProto.Value parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(androidx.datastore.preferences.PreferencesProto.Value prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code androidx.testing.Value}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          androidx.datastore.preferences.PreferencesProto.Value, Builder> implements
        // @@protoc_insertion_point(builder_implements:androidx.testing.Value)
        androidx.datastore.preferences.PreferencesProto.ValueOrBuilder {
      // Construct using androidx.datastore.preferences.PreferencesProto.Value.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @java.lang.Override
      public ValueCase
          getValueCase() {
        return instance.getValueCase();
      }

      public Builder clearValue() {
        copyOnWrite();
        instance.clearValue();
        return this;
      }


      /**
       * <code>optional bool boolean = 1;</code>
       * @return Whether the boolean field is set.
       */
      @java.lang.Override
      public boolean hasBoolean() {
        return instance.hasBoolean();
      }
      /**
       * <code>optional bool boolean = 1;</code>
       * @return The boolean.
       */
      @java.lang.Override
      public boolean getBoolean() {
        return instance.getBoolean();
      }
      /**
       * <code>optional bool boolean = 1;</code>
       * @param value The boolean to set.
       * @return This builder for chaining.
       */
      public Builder setBoolean(boolean value) {
        copyOnWrite();
        instance.setBoolean(value);
        return this;
      }
      /**
       * <code>optional bool boolean = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBoolean() {
        copyOnWrite();
        instance.clearBoolean();
        return this;
      }

      /**
       * <code>optional float float = 2;</code>
       * @return Whether the float field is set.
       */
      @java.lang.Override
      public boolean hasFloat() {
        return instance.hasFloat();
      }
      /**
       * <code>optional float float = 2;</code>
       * @return The float.
       */
      @java.lang.Override
      public float getFloat() {
        return instance.getFloat();
      }
      /**
       * <code>optional float float = 2;</code>
       * @param value The float to set.
       * @return This builder for chaining.
       */
      public Builder setFloat(float value) {
        copyOnWrite();
        instance.setFloat(value);
        return this;
      }
      /**
       * <code>optional float float = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFloat() {
        copyOnWrite();
        instance.clearFloat();
        return this;
      }

      /**
       * <code>optional int32 integer = 3;</code>
       * @return Whether the integer field is set.
       */
      @java.lang.Override
      public boolean hasInteger() {
        return instance.hasInteger();
      }
      /**
       * <code>optional int32 integer = 3;</code>
       * @return The integer.
       */
      @java.lang.Override
      public int getInteger() {
        return instance.getInteger();
      }
      /**
       * <code>optional int32 integer = 3;</code>
       * @param value The integer to set.
       * @return This builder for chaining.
       */
      public Builder setInteger(int value) {
        copyOnWrite();
        instance.setInteger(value);
        return this;
      }
      /**
       * <code>optional int32 integer = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInteger() {
        copyOnWrite();
        instance.clearInteger();
        return this;
      }

      /**
       * <code>optional int64 long = 4;</code>
       * @return Whether the long field is set.
       */
      @java.lang.Override
      public boolean hasLong() {
        return instance.hasLong();
      }
      /**
       * <code>optional int64 long = 4;</code>
       * @return The long.
       */
      @java.lang.Override
      public long getLong() {
        return instance.getLong();
      }
      /**
       * <code>optional int64 long = 4;</code>
       * @param value The long to set.
       * @return This builder for chaining.
       */
      public Builder setLong(long value) {
        copyOnWrite();
        instance.setLong(value);
        return this;
      }
      /**
       * <code>optional int64 long = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLong() {
        copyOnWrite();
        instance.clearLong();
        return this;
      }

      /**
       * <code>optional string string = 5;</code>
       * @return Whether the string field is set.
       */
      @java.lang.Override
      public boolean hasString() {
        return instance.hasString();
      }
      /**
       * <code>optional string string = 5;</code>
       * @return The string.
       */
      @java.lang.Override
      public java.lang.String getString() {
        return instance.getString();
      }
      /**
       * <code>optional string string = 5;</code>
       * @return The bytes for string.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getStringBytes() {
        return instance.getStringBytes();
      }
      /**
       * <code>optional string string = 5;</code>
       * @param value The string to set.
       * @return This builder for chaining.
       */
      public Builder setString(
          java.lang.String value) {
        copyOnWrite();
        instance.setString(value);
        return this;
      }
      /**
       * <code>optional string string = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearString() {
        copyOnWrite();
        instance.clearString();
        return this;
      }
      /**
       * <code>optional string string = 5;</code>
       * @param value The bytes for string to set.
       * @return This builder for chaining.
       */
      public Builder setStringBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setStringBytes(value);
        return this;
      }

      /**
       * <code>optional .androidx.testing.StringSet string_set = 6;</code>
       */
      @java.lang.Override
      public boolean hasStringSet() {
        return instance.hasStringSet();
      }
      /**
       * <code>optional .androidx.testing.StringSet string_set = 6;</code>
       */
      @java.lang.Override
      public androidx.datastore.preferences.PreferencesProto.StringSet getStringSet() {
        return instance.getStringSet();
      }
      /**
       * <code>optional .androidx.testing.StringSet string_set = 6;</code>
       */
      public Builder setStringSet(androidx.datastore.preferences.PreferencesProto.StringSet value) {
        copyOnWrite();
        instance.setStringSet(value);
        return this;
      }
      /**
       * <code>optional .androidx.testing.StringSet string_set = 6;</code>
       */
      public Builder setStringSet(
          androidx.datastore.preferences.PreferencesProto.StringSet.Builder builderForValue) {
        copyOnWrite();
        instance.setStringSet(builderForValue);
        return this;
      }
      /**
       * <code>optional .androidx.testing.StringSet string_set = 6;</code>
       */
      public Builder mergeStringSet(androidx.datastore.preferences.PreferencesProto.StringSet value) {
        copyOnWrite();
        instance.mergeStringSet(value);
        return this;
      }
      /**
       * <code>optional .androidx.testing.StringSet string_set = 6;</code>
       */
      public Builder clearStringSet() {
        copyOnWrite();
        instance.clearStringSet();
        return this;
      }

      /**
       * <code>optional double double = 7;</code>
       * @return Whether the double field is set.
       */
      @java.lang.Override
      public boolean hasDouble() {
        return instance.hasDouble();
      }
      /**
       * <code>optional double double = 7;</code>
       * @return The double.
       */
      @java.lang.Override
      public double getDouble() {
        return instance.getDouble();
      }
      /**
       * <code>optional double double = 7;</code>
       * @param value The double to set.
       * @return This builder for chaining.
       */
      public Builder setDouble(double value) {
        copyOnWrite();
        instance.setDouble(value);
        return this;
      }
      /**
       * <code>optional double double = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDouble() {
        copyOnWrite();
        instance.clearDouble();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:androidx.testing.Value)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new androidx.datastore.preferences.PreferencesProto.Value();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "value_",
              "valueCase_",
              "bitField0_",
              androidx.datastore.preferences.PreferencesProto.StringSet.class,
            };
            java.lang.String info =
                "\u0001\u0007\u0001\u0001\u0001\u0007\u0007\u0000\u0000\u0000\u0001:\u0000\u00024" +
                "\u0000\u00037\u0000\u00045\u0000\u0005;\u0000\u0006<\u0000\u00073\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<androidx.datastore.preferences.PreferencesProto.Value> parser = PARSER;
          if (parser == null) {
            synchronized (androidx.datastore.preferences.PreferencesProto.Value.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<androidx.datastore.preferences.PreferencesProto.Value>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:androidx.testing.Value)
    private static final androidx.datastore.preferences.PreferencesProto.Value DEFAULT_INSTANCE;
    static {
      Value defaultInstance = new Value();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Value.class, defaultInstance);
    }

    public static androidx.datastore.preferences.PreferencesProto.Value getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Value> PARSER;

    public static com.google.protobuf.Parser<Value> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface StringSetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:androidx.testing.StringSet)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated string strings = 1;</code>
     * @return A list containing the strings.
     */
    java.util.List<java.lang.String>
        getStringsList();
    /**
     * <code>repeated string strings = 1;</code>
     * @return The count of strings.
     */
    int getStringsCount();
    /**
     * <code>repeated string strings = 1;</code>
     * @param index The index of the element to return.
     * @return The strings at the given index.
     */
    java.lang.String getStrings(int index);
    /**
     * <code>repeated string strings = 1;</code>
     * @param index The index of the element to return.
     * @return The strings at the given index.
     */
    com.google.protobuf.ByteString
        getStringsBytes(int index);
  }
  /**
   * Protobuf type {@code androidx.testing.StringSet}
   */
  public  static final class StringSet extends
      com.google.protobuf.GeneratedMessageLite<
          StringSet, StringSet.Builder> implements
      // @@protoc_insertion_point(message_implements:androidx.testing.StringSet)
      StringSetOrBuilder {
    private StringSet() {
      strings_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    public static final int STRINGS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<java.lang.String> strings_;
    /**
     * <code>repeated string strings = 1;</code>
     * @return A list containing the strings.
     */
    @java.lang.Override
    public java.util.List<java.lang.String> getStringsList() {
      return strings_;
    }
    /**
     * <code>repeated string strings = 1;</code>
     * @return The count of strings.
     */
    @java.lang.Override
    public int getStringsCount() {
      return strings_.size();
    }
    /**
     * <code>repeated string strings = 1;</code>
     * @param index The index of the element to return.
     * @return The strings at the given index.
     */
    @java.lang.Override
    public java.lang.String getStrings(int index) {
      return strings_.get(index);
    }
    /**
     * <code>repeated string strings = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the strings at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringsBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          strings_.get(index));
    }
    private void ensureStringsIsMutable() {
      if (!strings_.isModifiable()) {
        strings_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(strings_);
       }
    }
    /**
     * <code>repeated string strings = 1;</code>
     * @param index The index to set the value at.
     * @param value The strings to set.
     */
    private void setStrings(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStringsIsMutable();
      strings_.set(index, value);
    }
    /**
     * <code>repeated string strings = 1;</code>
     * @param value The strings to add.
     */
    private void addStrings(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStringsIsMutable();
      strings_.add(value);
    }
    /**
     * <code>repeated string strings = 1;</code>
     * @param values The strings to add.
     */
    private void addAllStrings(
        java.lang.Iterable<java.lang.String> values) {
      ensureStringsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, strings_);
    }
    /**
     * <code>repeated string strings = 1;</code>
     */
    private void clearStrings() {
      strings_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string strings = 1;</code>
     * @param value The bytes of the strings to add.
     */
    private void addStringsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStringsIsMutable();
      strings_.add(value.toStringUtf8());
    }

    public static androidx.datastore.preferences.PreferencesProto.StringSet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static androidx.datastore.preferences.PreferencesProto.StringSet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static androidx.datastore.preferences.PreferencesProto.StringSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static androidx.datastore.preferences.PreferencesProto.StringSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static androidx.datastore.preferences.PreferencesProto.StringSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static androidx.datastore.preferences.PreferencesProto.StringSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static androidx.datastore.preferences.PreferencesProto.StringSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static androidx.datastore.preferences.PreferencesProto.StringSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static androidx.datastore.preferences.PreferencesProto.StringSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static androidx.datastore.preferences.PreferencesProto.StringSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static androidx.datastore.preferences.PreferencesProto.StringSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static androidx.datastore.preferences.PreferencesProto.StringSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(androidx.datastore.preferences.PreferencesProto.StringSet prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code androidx.testing.StringSet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          androidx.datastore.preferences.PreferencesProto.StringSet, Builder> implements
        // @@protoc_insertion_point(builder_implements:androidx.testing.StringSet)
        androidx.datastore.preferences.PreferencesProto.StringSetOrBuilder {
      // Construct using androidx.datastore.preferences.PreferencesProto.StringSet.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated string strings = 1;</code>
       * @return A list containing the strings.
       */
      @java.lang.Override
      public java.util.List<java.lang.String>
          getStringsList() {
        return java.util.Collections.unmodifiableList(
            instance.getStringsList());
      }
      /**
       * <code>repeated string strings = 1;</code>
       * @return The count of strings.
       */
      @java.lang.Override
      public int getStringsCount() {
        return instance.getStringsCount();
      }
      /**
       * <code>repeated string strings = 1;</code>
       * @param index The index of the element to return.
       * @return The strings at the given index.
       */
      @java.lang.Override
      public java.lang.String getStrings(int index) {
        return instance.getStrings(index);
      }
      /**
       * <code>repeated string strings = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the strings at the given index.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getStringsBytes(int index) {
        return instance.getStringsBytes(index);
      }
      /**
       * <code>repeated string strings = 1;</code>
       * @param index The index to set the value at.
       * @param value The strings to set.
       * @return This builder for chaining.
       */
      public Builder setStrings(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setStrings(index, value);
        return this;
      }
      /**
       * <code>repeated string strings = 1;</code>
       * @param value The strings to add.
       * @return This builder for chaining.
       */
      public Builder addStrings(
          java.lang.String value) {
        copyOnWrite();
        instance.addStrings(value);
        return this;
      }
      /**
       * <code>repeated string strings = 1;</code>
       * @param values The strings to add.
       * @return This builder for chaining.
       */
      public Builder addAllStrings(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllStrings(values);
        return this;
      }
      /**
       * <code>repeated string strings = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStrings() {
        copyOnWrite();
        instance.clearStrings();
        return this;
      }
      /**
       * <code>repeated string strings = 1;</code>
       * @param value The bytes of the strings to add.
       * @return This builder for chaining.
       */
      public Builder addStringsBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addStringsBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:androidx.testing.StringSet)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new androidx.datastore.preferences.PreferencesProto.StringSet();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "strings_",
            };
            java.lang.String info =
                "\u0001\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001a";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<androidx.datastore.preferences.PreferencesProto.StringSet> parser = PARSER;
          if (parser == null) {
            synchronized (androidx.datastore.preferences.PreferencesProto.StringSet.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<androidx.datastore.preferences.PreferencesProto.StringSet>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:androidx.testing.StringSet)
    private static final androidx.datastore.preferences.PreferencesProto.StringSet DEFAULT_INSTANCE;
    static {
      StringSet defaultInstance = new StringSet();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        StringSet.class, defaultInstance);
    }

    public static androidx.datastore.preferences.PreferencesProto.StringSet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<StringSet> PARSER;

    public static com.google.protobuf.Parser<StringSet> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
